version: '3.8'
services:
  auth:
    container_name: auth
    build:
      context: .
      dockerfile: ./build/services/auth.Dockerfile
    environment:
      AUTH_SERVER_HOST: "0.0.0.0"
      AUTH_SERVER_PORT: "8000"
    ports:
      - "8001:8000"
    develop:
      watch:
        - action: rebuild
          path: ./cmd/auth
        - action: rebuild
          path: ./internal/auth
        - action: rebuild
          path: ./internal/utils
        - action: rebuild
          path: ./pkg
        - action: rebuild
          path: ./go.mod
        - action: rebuild
          path: ./go.sum
        - action: sync+restart
          path: ./config/auth-conf.yaml
          target: /auth/auth-conf.yaml
  medication:
    container_name: medication
    build:
      context: .
      dockerfile: ./build/services/medication.Dockerfile
    env_file:
      - ".env"
    environment:
      MEDICATION_SERVER_HOST: "0.0.0.0"
      MEDICATION_SERVER_PORT: "8000"
      BASE_URL: "http://auth:8000"
      PATH: "/session"
      COOKIE_NAME: "session_id"
      COOKIE_DOMAIN: "auth"
      AUTH_TIMEOUT: "30s"
      CLIENT_API_HOST: ${CLIENT_API_HOST}
      SCAN_TIMEOUT: "10s"
    ports:
      - "8002:8000"
    develop:
      watch:
        - action: rebuild
          path: ./cmd/medication
        - action: rebuild
          path: ./internal/medication
        - action: rebuild
          path: ./internal/utils
        - action: rebuild
          path: ./pkg
        - action: rebuild
          path: ./go.mod
        - action: rebuild
          path: ./go.sum
        - action: sync+restart
          path: ./config/medication-conf.yaml
          target: /medication/medication-conf.yaml
    depends_on:
      mongodb:
        condition: service_started
  notifications:
    container_name: notifications
    build:
      context: .
      dockerfile: ./build/services/notifications.Dockerfile
    env_file:
      - ".env"
    environment:
      NOTIFICATIONS_SERVER_HOST: "0.0.0.0"
      NOTIFICATIONS_SERVER_PORT: "8000"
      BASE_URL: "http://auth:8000"
      PATH: "/session"
      COOKIE_NAME: "session_id"
      COOKIE_DOMAIN: "auth"
      AUTH_TIMEOUT: "30s"
      VAPID_PUBLIC_KEY: ${VAPID_PUBLIC_KEY}
      VAPID_PRIVATE_KEY: ${VAPID_PRIVATE_KEY}
      NOTIFICATIONS_TIMEOUT: "10s"
    ports:
      - "8003:8000"
    develop:
      watch:
        - action: rebuild
          path: ./cmd/notifications
        - action: rebuild
          path: ./internal/notifications
        - action: rebuild
          path: ./internal/utils
        - action: rebuild
          path: ./pkg
        - action: rebuild
          path: ./go.mod
        - action: rebuild
          path: ./go.sum
        - action: sync+restart
          path: ./config/notifications-conf.yaml
          target: /notifications/notifications-conf.yaml
  mongodb:
    container_name: mongodb
    build:
      context: .
      dockerfile: ./build/databases/medication-mongodb.Dockerfile
    env_file:
      - .env
    environment:
      # this variables are essential for start initialization.
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=${MEDICATION_MONGO_DATABASE}
    ports:
      - "27017:27017"
    volumes:
      - type: bind
        source: ../data_mongodb
        target: /data/db
